version: '3'

services:
  karaf:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
      - "8181:8181"
      - "44444:44444"
    volumes:
      - ./data:/opt/karaf/data
    environment:
      KARAF_VERSION: "4.4.4"
      KARAF_HOME: /opt/karaf