version: '3'

services:
  device:
    build:
      context: .
      dockerfile: Dockerfile.device
    ports:
      - "8102:8101"
      - "8182:8181"
      - "44445:44444"
    depends_on:
      - mosquitto
      - gateway
    volumes:
      - ./data/device:/opt/karaf/data
    environment:
      KARAF_VERSION: "4.4.4"
      KARAF_HOME: /opt/karaf

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8103:8101"
      - "8183:8181"
      - "44446:44444"
    depends_on:
      - mosquitto
    volumes:
      - ./data/gateway:/opt/karaf/data
    environment:
      KARAF_VERSION: "4.4.4"
      KARAF_HOME: /opt/karaf

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/labes2/repositories/wiser/infra/m2simulation/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf